#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	TC_STRING	258
#define	TC_ENCAPSULATED_STRING	259
#define	SECTION	260
#define	CFG_TRUE	261
#define	CFG_FALSE	262
#define	EXTENSION	263
#define	T_ZEND_EXTENSION	264
#define	T_ZEND_EXTENSION_TS	265
#define	T_ZEND_EXTENSION_DEBUG	266
#define	T_ZEND_EXTENSION_DEBUG_TS	267

