#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	TC_STRING	257
#define	TC_ENCAPSULATED_STRING	258
#define	SECTION	259
#define	CFG_TRUE	260
#define	CFG_FALSE	261
#define	EXTENSION	262
#define	T_ZEND_EXTENSION	263
#define	T_ZEND_EXTENSION_TS	264
#define	T_ZEND_EXTENSION_DEBUG	265
#define	T_ZEND_EXTENSION_DEBUG_TS	266

